export interface HostProvider {
  slug: string
  name: string
  tagline: string
  price: string
  rating: number
  badge: string
  badgeColor: string
  gradient: string
  emoji: string
  features: string[]
  affiliateUrl: string
  pros: string[]
  cons: string[]
  speed: string
  uptime: string
  support: string
}

export const hosts: HostProvider[] = [
  {
    slug: 'hostinger',
    name: 'Hostinger',
    tagline: 'Best value for beginners',
    price: '$2.99',
    rating: 4.8,
    badge: '#1 Pick',
    badgeColor: 'bg-yellow-400 text-yellow-900',
    gradient: 'bg-gradient-to-br from-indigo-500 to-purple-600',
    emoji: '🚀',
    features: ['100 GB NVMe SSD', 'Free domain 1 year', 'Free SSL', '99.9% uptime', '24/7 support'],
    affiliateUrl: 'https://www.hostinger.com/web-hosting?REFERRALCODE=OFMBZTOPRZSU',
    pros: [
      'Extremely affordable starting price',
      'Fast NVMe SSD storage',
      'Easy-to-use hPanel dashboard',
      'Free domain for first year',
      'AI website builder included',
    ],
    cons: [
      'Annual commitment required (no monthly billing)',
      'Renewal prices are higher than intro rates',
      'Support speed varies during peak hours',
    ],
    speed: '400ms avg',
    uptime: '99.93%',
    support: '24/7 Live Chat',
  },
  {
    slug: 'bluehost',
    name: 'Bluehost',
    tagline: 'WordPress.org recommended — but is it actually good?',
    price: '$2.95',
    rating: 3.9,
    badge: 'WP Official',
    badgeColor: 'bg-blue-100 text-blue-700',
    gradient: 'bg-gradient-to-br from-blue-500 to-cyan-500',
    emoji: '🌐',
    features: ['Free domain 1 year', '1-click WordPress', 'Free SSL', 'Unmetered bandwidth', 'Money-back guarantee'],
    affiliateUrl: 'https://www.bluehost.com',
    pros: [
      'Officially recommended by WordPress.org',
      'Very easy WordPress installation',
      'Beginner-friendly control panel',
      'Includes domain name registration',
      '30-day money-back guarantee',
    ],
    cons: [
      'Aggressive upsells during checkout',
      'Performance can be inconsistent',
      'Renewal prices significantly higher',
    ],
    speed: '650ms avg',
    uptime: '99.88%',
    support: '24/7 Live Chat + Phone',
  },
  {
    slug: 'wpengine',
    name: 'WP Engine',
    tagline: 'Best managed WordPress hosting',
    price: '$20',
    rating: 4.7,
    badge: 'Premium',
    badgeColor: 'bg-purple-100 text-purple-700',
    gradient: 'bg-gradient-to-br from-pink-500 to-rose-500',
    emoji: '⚡',
    features: ['Managed WordPress', 'Daily backups', 'Global CDN', 'Staging environment', 'Expert support'],
    affiliateUrl: 'https://wpengine.com',
    pros: [
      'Excellent speed and performance',
      'Developer-friendly tools and staging',
      'Free premium Genesis themes',
      'Expert WordPress-only support',
      '99.99% uptime guarantee',
    ],
    cons: [
      'Expensive for personal or small sites',
      'WordPress-only (no other CMS)',
      'Some popular plugins are blocked',
    ],
    speed: '130ms avg',
    uptime: '99.99%',
    support: '24/7 Live Chat + Phone',
  },
  {
    slug: 'cloudways',
    name: 'Cloudways',
    tagline: 'Best managed cloud hosting',
    price: '$11',
    rating: 4.7,
    badge: 'Cloud',
    badgeColor: 'bg-teal-100 text-teal-700',
    gradient: 'bg-gradient-to-br from-teal-500 to-cyan-600',
    emoji: '☁️',
    features: ['Managed cloud infra', 'Free SSL & Cloudflare CDN', 'Daily backups', '24/7 expert support', 'Instant scaling'],
    affiliateUrl: 'https://www.cloudways.com/en/?id=2170350',
    pros: [
      'Excellent scalability on demand',
      'Choice of AWS, GCP, DigitalOcean',
      'Outstanding performance metrics',
      'Team collaboration features',
      'Pay-as-you-go option available',
    ],
    cons: [
      'No email hosting included',
      'More complex setup for beginners',
      'No domain registration service',
    ],
    speed: '185ms avg',
    uptime: '99.97%',
    support: '24/7 Live Chat + Phone',
  },
  {
    slug: 'siteground',
    name: 'SiteGround',
    tagline: 'Premium shared hosting with great support',
    price: '$3.99',
    rating: 4.6,
    badge: 'Top Support',
    badgeColor: 'bg-orange-100 text-orange-700',
    gradient: 'bg-gradient-to-br from-orange-400 to-red-500',
    emoji: '🌍',
    features: ['10 GB Web Space', 'Free domain 1 year', 'Free SSL', 'Daily backups', 'Ultrafast PHP'],
    affiliateUrl: 'https://www.siteground.com',
    pros: [
      'Exceptional customer support (2 min avg response)',
      'Ultrafast PHP and proprietary caching',
      'Free automatic daily backups',
      'Free CDN and SSL included',
      '99.99% uptime guarantee',
    ],
    cons: [
      'Storage is limited compared to competitors',
      'Renewal prices are very high ($14.99+/mo)',
      'No Windows hosting',
    ],
    speed: '390ms avg',
    uptime: '99.99%',
    support: '24/7 Live Chat + Phone',
  },
  {
    slug: 'dreamhost',
    name: 'DreamHost',
    tagline: 'Privacy-focused WordPress recommended host',
    price: '$2.59',
    rating: 4.4,
    badge: 'WP Recommended',
    badgeColor: 'bg-sky-100 text-sky-700',
    gradient: 'bg-gradient-to-br from-sky-400 to-blue-500',
    emoji: '💤',
    features: ['Unlimited bandwidth', 'Free domain 1 year', 'Free SSL', '97-day money-back', 'Privacy protection'],
    affiliateUrl: 'https://www.dreamhost.com',
    pros: [
      'Recommended by WordPress.org',
      'Best-in-class 97-day money-back guarantee',
      'Free domain privacy included',
      'Unlimited bandwidth and storage on most plans',
      'Strong commitment to open-source',
    ],
    cons: [
      'No cPanel — custom panel can confuse beginners',
      'No phone support (chat and email only)',
      'Performance can be inconsistent',
    ],
    speed: '500ms avg',
    uptime: '99.95%',
    support: '24/7 Live Chat + Email',
  },
  {
    slug: 'godaddy',
    name: 'GoDaddy',
    tagline: 'The world\'s largest domain registrar',
    price: '$2.99',
    rating: 3.9,
    badge: 'Popular Brand',
    badgeColor: 'bg-green-100 text-green-700',
    gradient: 'bg-gradient-to-br from-green-500 to-emerald-600',
    emoji: '🐊',
    features: ['Unmetered bandwidth', 'Free domain 1 year', 'Free SSL (1st year)', '30-day money-back', 'Website builder'],
    affiliateUrl: 'https://www.godaddy.com',
    pros: [
      'Recognizable brand with 24/7 phone support',
      'Easy-to-use website builder',
      'Excellent domain management tools',
      'Wide range of hosting plans',
      'Free Microsoft 365 email (1 year)',
    ],
    cons: [
      'Performance lags behind competitors',
      'Aggressive upselling during checkout',
      'SSL is only free for the first year',
      'Renewal prices are very high',
    ],
    speed: '780ms avg',
    uptime: '99.88%',
    support: '24/7 Phone + Chat',
  },
  {
    slug: 'hostgator',
    name: 'HostGator',
    tagline: 'Budget hosting with flexible billing',
    price: '$2.75',
    rating: 4.0,
    badge: 'Budget Pick',
    badgeColor: 'bg-yellow-100 text-yellow-700',
    gradient: 'bg-gradient-to-br from-yellow-400 to-orange-500',
    emoji: '🐊',
    features: ['Unmetered bandwidth', 'Free domain 1 year', 'Free SSL', '45-day money-back', 'Free site migration'],
    affiliateUrl: 'https://www.hostgator.com',
    pros: [
      'Flexible monthly billing available',
      'Long 45-day money-back guarantee',
      'Unmetered bandwidth on all plans',
      'Free website migration',
      '24/7 phone and chat support',
    ],
    cons: [
      'Performance is average to below-average',
      'Lots of upsells during checkout',
      'Renewal rates significantly higher',
      'Owned by EIG (affects quality consistency)',
    ],
    speed: '700ms avg',
    uptime: '99.90%',
    support: '24/7 Phone + Chat',
  },
  {
    slug: 'kinsta',
    name: 'Kinsta',
    tagline: 'Premium Google Cloud WordPress hosting',
    price: '$35',
    rating: 4.9,
    badge: 'Premium',
    badgeColor: 'bg-pink-100 text-pink-700',
    gradient: 'bg-gradient-to-br from-pink-500 to-fuchsia-600',
    emoji: '🏔️',
    features: ['Google Cloud C2 machines', 'Free SSL & CDN', 'Daily automated backups', 'Staging environment', 'Expert 24/7 support'],
    affiliateUrl: 'https://kinsta.com',
    pros: [
      'Fastest WordPress hosting we\'ve ever tested',
      'Google Cloud Platform infrastructure',
      'Outstanding 24/7 expert support',
      'Advanced staging and dev tools',
      'Free Cloudflare Enterprise CDN',
    ],
    cons: [
      'Very expensive starting price ($35/mo)',
      'WordPress-only hosting',
      'Strict plugin restrictions',
    ],
    speed: '150ms avg',
    uptime: '99.99%',
    support: '24/7 Live Chat (Experts Only)',
  },
  {
    slug: 'namecheap',
    name: 'Namecheap',
    tagline: 'Ultra-budget hosting with solid basics',
    price: '$1.98',
    rating: 4.1,
    badge: 'Cheapest',
    badgeColor: 'bg-orange-100 text-orange-700',
    gradient: 'bg-gradient-to-br from-orange-500 to-yellow-500',
    emoji: '💰',
    features: ['20 GB SSD', 'Free domain 1 year', 'Free SSL', 'Unmetered bandwidth', 'cPanel'],
    affiliateUrl: 'https://www.namecheap.com',
    pros: [
      'Lowest starting price on the market',
      'Free WhoisGuard domain privacy',
      'Easy-to-use cPanel control panel',
      'Transparent pricing with low renewals',
      'Good for simple static sites',
    ],
    cons: [
      'Support can be slow and inconsistent',
      'Performance is below average',
      'Not ideal for high-traffic or dynamic sites',
    ],
    speed: '620ms avg',
    uptime: '99.90%',
    support: '24/7 Live Chat',
  },
  {
    slug: 'a2hosting',
    name: 'A2 Hosting',
    tagline: 'Speed-obsessed shared hosting',
    price: '$2.99',
    rating: 4.5,
    badge: 'Speed Pick',
    badgeColor: 'bg-red-100 text-red-700',
    gradient: 'bg-gradient-to-br from-red-500 to-rose-600',
    emoji: '⚡',
    features: ['100 GB NVMe SSD', 'Free domain', 'Free SSL', 'Turbo servers (optional)', 'Developer-friendly'],
    affiliateUrl: 'https://www.a2hosting.com',
    pros: [
      'Turbo servers with 20x faster PHP',
      'NVMe SSD storage on all plans',
      'Developer-friendly with SSH, Git, WP-CLI',
      'Anytime money-back guarantee',
      'Free SSL and site migration',
    ],
    cons: [
      'Turbo speed requires higher-tier plan',
      'Support quality is inconsistent',
      'Renewal rates are high',
    ],
    speed: '350ms avg',
    uptime: '99.93%',
    support: '24/7 Live Chat + Phone',
  },
]

export function getHostBySlug(slug: string): HostProvider | undefined {
  return hosts.find((h) => h.slug === slug)
}

export function getAllHostSlugs(): string[] {
  return hosts.map((h) => h.slug)
}
